# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72ba89c64bc7a778c0ca73c85936e5bd48a23391e278e303a6d3f20fd6d0e810f12589a21b0d62f430416bc5f3873570eb294ec00a57d7c828ac8433fdc96b81

test:
  secret_key_base: ae2cf81454bb61662ea9a3dd35a47bb2f2e6442ca0c068859f492a6aace788819aaf2f34d3df5ff7f79a670db3ab50b73b391361551cb4b1a3d8c64097dec049

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
